version: "3"
services:
  app: &app
    container_name: memo
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
      target: PYTHON
    volumes:
      - type: bind
        source: app
        target: /work/app
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      - db
    command: python3 app.py
  tailwind:
    container_name: memo-tailwind
    <<: *app
    build:
      target: TAILWIND
    command: npm run build-css
    ports: []
  db:
    container_name: memo-postgres
    image: postgres:latest
    restart: always
    ports:
      - '5431:5431'
    volumes:
      - type: bind
        source: db
        target: /var/lib/postgresql/data
    env_file:
      - .env
